"""

Revision ID: 6e1ca8ef324c
Revises: 0c843f782478
Create Date: 2023-07-06 12:01:52.959215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e1ca8ef324c'
down_revision = '0c843f782478'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('disabled', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_users_disabled'), 'users', ['disabled'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_disabled'), table_name='users')
    op.drop_column('users', 'disabled')
    # ### end Alembic commands ###
